version: "3.7"
services:

    gitlab_helper_traefik:
        image: "traefik:v2.2"
        container_name: "gitlab_helper_traefik"
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web-secure.address=:443"
            - "--entrypoints.web.forwardedheaders.insecure"
            - "--entrypoints.web.proxyprotocol.insecure"
            - "--certificatesresolvers.letsencrypt.acme.email=adrixop95@gmail.com"
            - "--certificatesresolvers.letsencrypt.acme.storage=/ssl/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
        labels:
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "traefik_le:/ssl"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - gitlab_helper_network
        restart: unless-stopped

    gitlab_helper_frontend:
        image: "adrixop95/gitlab-helper-frontend:development"
        container_name: "gitlab_helper_frontend"
        environment: 
            - HOSTNAME=${http}://${URL}/
        labels:
            - traefik.enable=true
            - traefik.http.routers.gitlab_helper_frontend.rule=Host(`${URL}`)
            - traefik.http.services.gitlab_helper_frontend.loadbalancer.server.port=80
            - traefik.http.routers.gitlab_helper_frontend.entrypoints=web-secure
            - traefik.http.middlewares.gitlab_helper_frontend.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
            - traefik.http.middlewares.gitlab_helper_frontend.headers.accesscontrolalloworigin=origin-list-or-null
            - traefik.http.middlewares.gitlab_helper_frontend.headers.accesscontrolmaxage=100
            - traefik.http.middlewares.gitlab_helper_frontend.headers.addvaryheader=true
            - traefik.http.routers.gitlab_helper_frontend.tls=true
            - traefik.http.routers.gitlab_helper_frontend.tls.certresolver=letsencrypt
        networks:
            - gitlab_helper_network
        restart: unless-stopped

    gitlab_helper_backend:
        image: "adrixop95/gitlab-helper-backend:latest"
        container_name: "gitlab_helper_backend"
        environment:
            - PRIVATE_TOKEN=urToken
            - GITLAB_URL=https://gitlab.com/
        labels:
            - traefik.enable=true
            - traefik.http.routers.gitlab_helper_backend.rule=Host(`${URL}`) && PathPrefix (`/groups`)
            - traefik.http.services.gitlab_helper_backend.loadbalancer.server.port=8005
            - traefik.http.routers.gitlab_helper_backend.entrypoints=web-secure
            - traefik.http.middlewares.gitlab_helper_backend.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
            - traefik.http.middlewares.gitlab_helper_backend.headers.accesscontrolalloworigin=origin-list-or-null
            - traefik.http.middlewares.gitlab_helper_backend.headers.accesscontrolmaxage=100
            - traefik.http.middlewares.gitlab_helper_backend.headers.addvaryheader=true
            - traefik.http.routers.gitlab_helper_backend.tls=true
            - traefik.http.routers.gitlab_helper_backend.tls.certresolver=letsencrypt
        networks:
            - gitlab_helper_network
        restart: unless-stopped

volumes: 
    traefik_le:

networks:
    gitlab_helper_network:
        name: gitlab_helper_network
